### Add new book
POST localhost:8080/book
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "Go CQRS",
  "isbn": {
    "prefix": 123,
    "country_code": 12,
    "publisher_code": 22,
    "book_code": 23,
    "control_number": 0
  }
}